### ISSUE TITLE
[Feature Request] MacOS version

### ISSUE THREAD

**Issue by lothar-cell** [Arcitec/iconix#1]
Hey, MacOS version would be great to have!

**Comment by Arcitec** [comment]
Hi, thanks for your interest in this project. :)

There's nothing to do for Macs. They use a completely different method of replacing app icons, by attaching the new icon as a resource stream on the application's bundle. There are no files or anything that we could edit with iconix.

This is how you replace app icons on Mac:

- Navigate to your Applications folder.
- Right-click the app you wish to customize.
- Choose "Get Info".
- Drag and drop your custom icon on top of the default one in the information window.
- [Feel free to use my icon packs from this project](https://github.com/Arcitec/iconix/tree/main/icon_packs).
- You may need to use a "PNG to ICNS converter" (such as this [online one](https://cloudconvert.com/png-to-icns)) if it won't accept the PNG directly.

Example:

![Animation showing how to replace icons on Mac](https://i.imgur.com/qgD9niV.gif)
