### ISSUE TITLE
[Question] How to change the icon for Vesktop Flatpak?

### ISSUE THREAD

**Issue by zribe** [Arcitec/iconix#3]
the folder that needs changing is:
`/var/lib/flatpak/app/dev.vencord.Vesktop/x86_64/stable/5ef97a0229c851efc97b7562f997e6c37bb0b0e73c107b21dad2246224d4fa32/files/bin/vesktop/usr/share/icons/hicolor/`

for flatpak.

**Comment by Arcitec** [comment]
Alternative icon locations is already supported by this app, but you're right that I should add instructions for how to do it. I don't use the Vesktop Flatpak so I didn't think about it. :)

Can you try this command? If it works for you, I'll add it to the README update for v2.2.0. :)

`./iconix -n dev.vencord.Vesktop -d`

Edit: I just installed the Flatpak and tried it. That solution works for me. I'll add it to the instructions after you confirm on your end.

**Comment by zribe** [comment]
il try

**Comment by zribe** [comment]
its been 12 mins and the icon has not changed yet

**Comment by Arcitec** [comment]
> its been 12 mins and the icon has not changed yet

Oof, what desktop environment are you using?

I use GNOME 46 and installed the Vesktop Flatpak and ran the test about 10 minutes ago, and it worked.

**Comment by zribe** [comment]
using gnome 42.9

**Comment by zribe** [comment]
holy! wait! it suddenly worked now! the icon just changed randomly out of nowhere!

**Comment by Arcitec** [comment]
Okay that's good.

Did you do the other step which the patcher suggests?

> "Patching complete! It may take a few minutes for the new icon to become active in your desktop environment.
> 
> If you're on GNOME, opening the Activities Overview and searching for Vesktop seems to help it detect the change a bit faster."

**Comment by zribe** [comment]
Yes

**Comment by Arcitec** [comment]
> Yes

I see. Sometimes even that trick takes a long time to catch up. But the longest I've seen is about a minute or two.

> holy! wait! it suddenly worked now! the icon just changed randomly out of nowhere!

Yeah that's GNOME caching the old icon until it realizes it has changed. :)

Can you do one more test for me?

Open the Vesktop app, then open the GNOME Overview and look at the Vesktop window's app icon in the overview. Did it get replaced too? It should have.

**Comment by zribe** [comment]
Yep it did! thats wonderful! finally

**Comment by Arcitec** [comment]
> Yep it did! thats wonderful! finally

Thanks a lot for verifying the Flatpak support too. That's great news. :) I'll publish the new version with these instructions for everyone very shortly. :) Have a nice day.

**Comment by Arcitec** [comment]
@ZribeDev v2.2.0 is officially released now. By the way, in case you didn't see them, there's lots of icons in the repository if you want to try something new and fresh. :)

For example, here's a very clean icon:

```sh
./iconix -n dev.vencord.Vesktop -i icon_packs/motion_fans/silver_noir/circle.png
```

If you prefer Discord's purple color, there are several remixes of that in the `classic_remix` theme directories. Check it out and have fun. :)

**Comment by zribe** [comment]
The silver noir is the one I am using! It looks great

**Comment by Arcitec** [comment]
Thanks, glad to hear that you like it! :) Have an awesome day!

**Comment by Mavarice** [comment]
> Alternative icon locations is already supported by this app, but you're right that I should add instructions for how to do it. I don't use the Vesktop Flatpak so I didn't think about it. :)
> 
> Can you try this command? If it works for you, I'll add it to the README update for v2.2.0. :)
> 
> `./iconix -n dev.vencord.Vesktop -d`
> 
> Edit: I just installed the Flatpak and tried it. That solution works for me. I'll add it to the instructions after you confirm on your end.

By the way, you haven't updated the readme, I found this while trying to patch my flatpak version. It did work and solved the issue so I think it's worth adding.

**Comment by Mavarice** [comment]
Nevermind, you absolutely did. I'm not sure how I missed it the first time reading it :facepalm:
